name: RUN test
on:
  schedule:
    - cron: '0 0 * * *' #毎日00:00
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # 以下が実際のステップ
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # - name: Build project
    #   uses: actions/setup-node@v2
    #   env:
    #     PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    #   with:
    #     args: npm install

    - name: Install Dependencies
      uses: actions/setup-node@v2
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install

    - run: npm install

    - run: mkdir ./test/download -p
    - run: mkdir ./test/puppeteerScreenShot -p

    - name: Test Code
      uses: mujo-code/puppeteer-headful@v2
      with:
        args: npm run test
        
    - run: ls ./test/download
        
    - name: Save Downloaded Files
      uses: actions/upload-artifact@v3
      with:
        name: Downloaded Files
        path: ./test/download/* # or path/to/artifact

    - run: ls ./test/puppeteerScreenShot

    - name: Save ScreenShots
      uses: actions/upload-artifact@v3
      with:
        name: ScreenShots
        path: ./test/puppeteerScreenShot/* # or path/to/artifact